# Generated by Django 2.0.7 on 2018-09-04 03:22

from django.db import migrations
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180904_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certifications',
            old_name='path',
            new_name='cover_img_path',
        ),
        migrations.AddField(
            model_name='certifications',
            name='all_img_paths',
            field=separatedvaluesfield.models.SeparatedValuesField(default=['test'], max_length=512),
            preserve_default=False,
        ),
    ]
