# Generated by Django 2.0.7 on 2018-09-04 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20180904_1122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certifications',
            new_name='Certificates',
        ),
    ]
